package dns

import (
	"net"
	"os"
	"path/filepath"
	"testing"
)

func TestParseResolvConf(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		wantIPs  []string
	}{
		{
			name: "single nameserver",
			content: `# Generated by Docker
nameserver 192.168.65.7
`,
			wantIPs: []string{"192.168.65.7"},
		},
		{
			name: "multiple nameservers",
			content: `nameserver 8.8.8.8
nameserver 8.8.4.4
search example.com
`,
			wantIPs: []string{"8.8.8.8", "8.8.4.4"},
		},
		{
			name: "skips IPv6",
			content: `nameserver 1.1.1.1
nameserver ::1
nameserver 2001:4860:4860::8888
nameserver 9.9.9.9
`,
			wantIPs: []string{"1.1.1.1", "9.9.9.9"},
		},
		{
			name:    "comments and blanks only",
			content: "# this is a comment\n\n; another comment\n",
			wantIPs: nil,
		},
		{
			name:    "empty file",
			content: "",
			wantIPs: nil,
		},
		{
			name: "extra whitespace",
			content: `  nameserver   10.0.0.1  
	nameserver	172.16.0.1
`,
			wantIPs: []string{"10.0.0.1", "172.16.0.1"},
		},
		{
			name:    "invalid IP ignored",
			content: "nameserver not-an-ip\nnameserver 1.2.3.4\n",
			wantIPs: []string{"1.2.3.4"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "resolv.conf")
			if err := os.WriteFile(path, []byte(tt.content), 0644); err != nil {
				t.Fatalf("write test file: %v", err)
			}
			got := parseResolvConf(path)
			if len(got) != len(tt.wantIPs) {
				t.Fatalf("got %d IPs, want %d: %v", len(got), len(tt.wantIPs), got)
			}
			for i, want := range tt.wantIPs {
				if !got[i].Equal(net.ParseIP(want)) {
					t.Errorf("IP[%d] = %s, want %s", i, got[i], want)
				}
			}
		})
	}
}

func TestParseResolvConfMissingFile(t *testing.T) {
	got := parseResolvConf("/nonexistent/resolv.conf")
	if got != nil {
		t.Errorf("expected nil for missing file, got %v", got)
	}
}
