// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type LeashdPolicyLpmKey struct {
	Prefixlen uint32
	Ip        uint32
}

type LeashdPolicyVal struct {
	Verdict uint8
	Pad     [3]uint8
}

// LoadLeashd returns the embedded CollectionSpec for Leashd.
func LoadLeashd() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LeashdBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Leashd: %w", err)
	}

	return spec, err
}

// LoadLeashdObjects loads Leashd and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*LeashdObjects
//	*LeashdPrograms
//	*LeashdMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadLeashdObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadLeashd()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// LeashdSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LeashdSpecs struct {
	LeashdProgramSpecs
	LeashdMapSpecs
}

// LeashdSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LeashdProgramSpecs struct {
	CgroupSkbEgress  *ebpf.ProgramSpec `ebpf:"cgroup_skb_egress"`
	KprobeTcpConnect *ebpf.ProgramSpec `ebpf:"kprobe_tcp_connect"`
	KprobeUdpConnect *ebpf.ProgramSpec `ebpf:"kprobe_udp_connect"`
}

// LeashdMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type LeashdMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	PolicyMap      *ebpf.MapSpec `ebpf:"policy_map"`
	TrackedCgroups *ebpf.MapSpec `ebpf:"tracked_cgroups"`
}

// LeashdObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadLeashdObjects or ebpf.CollectionSpec.LoadAndAssign.
type LeashdObjects struct {
	LeashdPrograms
	LeashdMaps
}

func (o *LeashdObjects) Close() error {
	return _LeashdClose(
		&o.LeashdPrograms,
		&o.LeashdMaps,
	)
}

// LeashdMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadLeashdObjects or ebpf.CollectionSpec.LoadAndAssign.
type LeashdMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	PolicyMap      *ebpf.Map `ebpf:"policy_map"`
	TrackedCgroups *ebpf.Map `ebpf:"tracked_cgroups"`
}

func (m *LeashdMaps) Close() error {
	return _LeashdClose(
		m.Events,
		m.PolicyMap,
		m.TrackedCgroups,
	)
}

// LeashdPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadLeashdObjects or ebpf.CollectionSpec.LoadAndAssign.
type LeashdPrograms struct {
	CgroupSkbEgress  *ebpf.Program `ebpf:"cgroup_skb_egress"`
	KprobeTcpConnect *ebpf.Program `ebpf:"kprobe_tcp_connect"`
	KprobeUdpConnect *ebpf.Program `ebpf:"kprobe_udp_connect"`
}

func (p *LeashdPrograms) Close() error {
	return _LeashdClose(
		p.CgroupSkbEgress,
		p.KprobeTcpConnect,
		p.KprobeUdpConnect,
	)
}

func _LeashdClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed leashd_bpfeb.o
var _LeashdBytes []byte
