// Package bpf wraps the cilium/ebpf-generated types for leashd's eBPF programs.
//
// This file provides stub types so the package compiles before running
// `go generate` (which requires clang and vmlinux.h).
// Running `make generate` replaces these stubs with the real generated code.
//
// DO NOT EDIT — generated by bpf2go after running `make generate`.
// This stub is kept for initial compilation only.
package bpf

import (
	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/ringbuf"
)

// LeashdObjects contains all maps and programs loaded from the leashd ELF.
// Generated by bpf2go; this is a stub for pre-generate compilation.
type LeashdObjects struct {
	LeashdMaps
	LeashdPrograms
}

// Close releases all eBPF resources held by the objects.
func (o *LeashdObjects) Close() {
	o.LeashdMaps.Close()
	o.LeashdPrograms.Close()
}

// LeashdMaps contains all BPF maps.
type LeashdMaps struct {
	PolicyMap      *ebpf.Map `ebpf:"policy_map"`
	TrackedCgroups *ebpf.Map `ebpf:"tracked_cgroups"`
	Events         *ebpf.Map `ebpf:"events"`
}

func (m *LeashdMaps) Close() {
	if m.PolicyMap != nil {
		_ = m.PolicyMap.Close()
	}
	if m.TrackedCgroups != nil {
		_ = m.TrackedCgroups.Close()
	}
	if m.Events != nil {
		_ = m.Events.Close()
	}
}

// LeashdPrograms contains all BPF programs.
type LeashdPrograms struct {
	KprobeTcpConnect *ebpf.Program `ebpf:"kprobe_tcp_connect"`
	KprobeUdpConnect *ebpf.Program `ebpf:"kprobe_udp_connect"`
	CgroupSkbEgress  *ebpf.Program `ebpf:"cgroup_skb_egress"`
}

func (p *LeashdPrograms) Close() {
	if p.KprobeTcpConnect != nil {
		_ = p.KprobeTcpConnect.Close()
	}
	if p.KprobeUdpConnect != nil {
		_ = p.KprobeUdpConnect.Close()
	}
	if p.CgroupSkbEgress != nil {
		_ = p.CgroupSkbEgress.Close()
	}
}

// loadLeashdObjects loads the leashd eBPF programs and maps from the embedded ELF.
// This stub returns an error — the real implementation is generated by bpf2go.
func loadLeashdObjects(obj *LeashdObjects, opts *ebpf.CollectionOptions) error {
	return &ebpf.VerifierError{} // replaced by go generate
}

// Ensure ringbuf import is used.
var _ *ringbuf.Reader
