// Package bpf wraps the cilium/ebpf-generated types for leashd's eBPF programs.
//
// This file provides stub types so the package compiles before running
// `go generate` (which requires clang + vmlinux.h).
// `make generate` deletes this file and replaces it with the real bpf2go output.
package bpf

import (
	"errors"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/ringbuf"
)

// LeashdObjects contains all maps and programs loaded from the leashd ELF.
// Generated by bpf2go; this stub is replaced by `make generate`.
type LeashdObjects struct {
	LeashdMaps
	LeashdPrograms
}

// Close releases all eBPF resources held by the objects.
func (o *LeashdObjects) Close() error {
	return errors.Join(o.LeashdMaps.Close(), o.LeashdPrograms.Close())
}

// LeashdMaps contains all BPF maps.
type LeashdMaps struct {
	PolicyMap      *ebpf.Map `ebpf:"policy_map"`
	TrackedCgroups *ebpf.Map `ebpf:"tracked_cgroups"`
	Events         *ebpf.Map `ebpf:"events"`
}

func (m *LeashdMaps) Close() error {
	var errs []error
	if m.PolicyMap != nil {
		errs = append(errs, m.PolicyMap.Close())
	}
	if m.TrackedCgroups != nil {
		errs = append(errs, m.TrackedCgroups.Close())
	}
	if m.Events != nil {
		errs = append(errs, m.Events.Close())
	}
	return errors.Join(errs...)
}

// LeashdPrograms contains all BPF programs.
type LeashdPrograms struct {
	KprobeTcpConnect *ebpf.Program `ebpf:"kprobe_tcp_connect"`
	KprobeUdpConnect *ebpf.Program `ebpf:"kprobe_udp_connect"`
	CgroupSkbEgress  *ebpf.Program `ebpf:"cgroup_skb_egress"`
}

func (p *LeashdPrograms) Close() error {
	var errs []error
	if p.KprobeTcpConnect != nil {
		errs = append(errs, p.KprobeTcpConnect.Close())
	}
	if p.KprobeUdpConnect != nil {
		errs = append(errs, p.KprobeUdpConnect.Close())
	}
	if p.CgroupSkbEgress != nil {
		errs = append(errs, p.CgroupSkbEgress.Close())
	}
	return errors.Join(errs...)
}

// loadLeashdObjects is a stub — replaced by go generate.
func loadLeashdObjects(obj *LeashdObjects, _ *ebpf.CollectionOptions) error {
	return errors.New("BPF programs not compiled: run `make generate` first")
}

// Ensure ringbuf import is used.
var _ *ringbuf.Reader
